version: '3.7'
services:
  api1:
    build: .
    #entrypoint: .docker/app/entrypoint.sh
    hostname: api1
    restart: always
    expose:
      - '80'
    depends_on:
      - database
      - redis
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_NAME=rinha
      - DATABASE_USER=root
      - DATABASE_PASSWORD=rinha123
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
  api2:
    build: .
    #entrypoint: .docker/app/entrypoint.sh
    hostname: api2
    restart: always
    expose:
      - '80'
    depends_on:
      - database
      - redis
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_NAME=rinha
      - DATABASE_USER=root
      - DATABASE_PASSWORD=rinha123
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
  nginx:
    image: nginx:latest
    container_name: rinha-nginx
    restart: always
    depends_on:
      - api1
    ports:
      - '9999:9999'
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
  database:
    image: mysql:latest
    container_name: rinha-database
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rinha123
      MYSQL_DATABASE: rinha
    command: --init-file /data/application/init.sql
    volumes:
      - .docker/database/init.sql:/data/application/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1.5G
  redis:
    image: redis:latest
    container_name: rinha-redis
    restart: always
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256GB
